# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z1_c/PYNQ-Z1_C.xdc

# IP: E:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_32x256 || ORIG_REF_NAME==blk_mem_gen_0_32x256} -quiet] -quiet

# Block Designs: bd/DSPProc_design/DSPProc_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design || ORIG_REF_NAME==DSPProc_design} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_processing_system7_0_0/DSPProc_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_processing_system7_0_0 || ORIG_REF_NAME==DSPProc_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_DSPProc_0_0/DSPProc_design_DSPProc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_DSPProc_0_0 || ORIG_REF_NAME==DSPProc_design_DSPProc_0_0} -quiet] -quiet

# IP: E:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_32x256 || ORIG_REF_NAME==blk_mem_gen_0_32x256} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_axi_gpio_0_0/DSPProc_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_axi_gpio_0_0 || ORIG_REF_NAME==DSPProc_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_continue_proc_0/DSPProc_design_continue_proc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_continue_proc_0 || ORIG_REF_NAME==DSPProc_design_continue_proc_0} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_continue_proc_1/DSPProc_design_continue_proc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_continue_proc_1 || ORIG_REF_NAME==DSPProc_design_continue_proc_1} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_continue_proc_2/DSPProc_design_continue_proc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_continue_proc_2 || ORIG_REF_NAME==DSPProc_design_continue_proc_2} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_continue_proc_3/DSPProc_design_continue_proc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_continue_proc_3 || ORIG_REF_NAME==DSPProc_design_continue_proc_3} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_continue_proc_4 || ORIG_REF_NAME==DSPProc_design_continue_proc_4} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_xbar_0/DSPProc_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_xbar_0 || ORIG_REF_NAME==DSPProc_design_xbar_0} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_ps7_0_axi_periph_0/DSPProc_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==DSPProc_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_rst_ps7_0_100M_0/DSPProc_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==DSPProc_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DSPProc_design/ip/DSPProc_design_auto_pc_0/DSPProc_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSPProc_design_auto_pc_0 || ORIG_REF_NAME==DSPProc_design_auto_pc_0} -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256_ooc.xdc

# XDC: e:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256_ooc.xdc

# XDC: bd/DSPProc_design/DSPProc_design_ooc.xdc
