# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/top/f7/vicilab/sample_projects/applications/DSPProcFolders/DSPProc_S21/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_32x256 || ORIG_REF_NAME==blk_mem_gen_0_32x256} -quiet] -quiet
