# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_DSPProc_0_0/DSPProc_design_DSPProc_0_0.xci
# IP: The module: 'DSPProc_design_DSPProc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_32x256 || ORIG_REF_NAME==blk_mem_gen_0_32x256} -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256_ooc.xdc

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_DSPProc_0_0/DSPProc_design_DSPProc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_DSPProc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_DSPProc_0_0/DSPProc_design_DSPProc_0_0.xci
# IP: The module: 'DSPProc_design_DSPProc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_32x256 || ORIG_REF_NAME==blk_mem_gen_0_32x256} -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/memory/sourceMem_32x256BRAM/blk_mem_gen_0_32x256/blk_mem_gen_0_32x256_ooc.xdc

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_DSPProc_0_0/DSPProc_design_DSPProc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_DSPProc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
