# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4.xci
# IP: The module: 'DSPProc_design_continue_proc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_continue_proc_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_continue_proc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_continue_proc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4.xci
# IP: The module: 'DSPProc_design_continue_proc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_continue_proc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_continue_proc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/BE_Project/Project/Project_files/DSPProc/topLevel/DSPProc/xilinxprj/DSPProc_all.srcs/sources_1/bd/DSPProc_design/ip/DSPProc_design_continue_proc_4/DSPProc_design_continue_proc_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSPProc_design_continue_proc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
